# Site Settings
# remote_theme: sujaykundu777/devlopr-jekyll

theme: jekyll-theme-hacker

footer: 'follow me on <a href="https://twitter.com/jordan_n_marr">twitter</a>'

plugins:
  - jekyll-remote-theme
