# Site Settings
remote_theme: bitbrain/jekyll-dash

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

dash:  
    social_links:
        - url: https://twitter.com/jordan_n_marr
          icon: twitter-square
          color: cyan
        - url: https://github.com/JordanMarr
          icon: github-square
          color: purple

# theme: jekyll-theme-hacker

url: https://jordanmarr.github.io

plugins:
  - jekyll-remote-theme
